apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodetestapp-helm.fullname" . }}
  labels:
    {{- include "nodetestapp-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodetestapp-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodetestapp-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodetestapp-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: MONGODB_URI
              value: mongodb://mongo:27017/prod
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: nodetestapp-secret    
                  key: secret
            - name: NODE_ENV
              value: {{ .Values.env }}

---
apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Values.namespace }}