{{- $fullName := include "nodetestapp-helm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.domain_name }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: 80
